//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_v1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
       
        public int AracTipiID { get; set; }
        public string AracTipi { get; set; }
        public string AracMarka { get; set; }
        public string AracModel { get; set; }
        public string AracPlaka { get; set; }
        public Nullable<int> AracModelYil { get; set; }
        public string AracRenk { get; set; }
        public string Kapasite_KG { get; set; }
        public string Kapasite_m3 { get; set; }
    }
}
